In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn.datasets import load_iris
data =load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
X =data.data
y =data.target

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X ,y,test_size=0.33,random_state=42)

In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train =scaler.fit_transform(X_train)

In [6]:
X_train

array([[-0.13835603, -0.26550845,  0.22229072,  0.10894943],
       [ 2.14752625, -0.02631165,  1.61160773,  1.18499319],
       [-0.25866563, -0.02631165,  0.39595535,  0.37796037],
       [-0.8602136 ,  1.16967238, -1.39857913, -1.37061074],
       [ 2.26783585, -0.50470526,  1.66949594,  1.05048772],
       [-0.01804644, -0.74390206,  0.16440251, -0.29456698],
       [-0.739904  ,  0.93047557, -1.39857913, -1.37061074],
       [-0.98052319,  1.16967238, -1.45646733, -1.23610527],
       [-0.8602136 ,  1.88726279, -1.10913808, -1.1015998 ],
       [-0.98052319, -2.4182797 , -0.18292674, -0.29456698],
       [ 0.58350153, -0.74390206,  0.62750818,  0.78147678],
       [-1.22114238,  0.93047557, -1.10913808, -1.37061074],
       [-0.98052319, -0.02631165, -1.28280271, -1.37061074],
       [-0.8602136 ,  0.69127877, -1.2249145 , -0.96709433],
       [-0.25866563, -0.74390206,  0.22229072,  0.10894943],
       [-0.8602136 ,  0.93047557, -1.34069092, -1.37061074],
       [-0.13835603, -0.

In [7]:
from sklearn.decomposition import PCA
pca =PCA(n_components=3)
pca.fit_transform(X_train)

array([[ 1.80806614e-01, -2.89949359e-01,  1.33781908e-01],
       [ 2.75947391e+00,  7.94235451e-01, -6.02767255e-01],
       [ 3.17594511e-01, -9.45982904e-02,  4.70709135e-01],
       [-2.32440574e+00,  7.19534192e-01, -1.46453582e-01],
       [ 2.89034253e+00,  3.83181790e-01, -8.82206238e-01],
       [ 9.05159418e-02, -7.14099562e-01, -3.31353421e-01],
       [-2.20600792e+00,  5.37801954e-01, -2.90454426e-01],
       [-2.34527922e+00,  6.82952398e-01,  1.88853139e-02],
       [-2.16615986e+00,  1.40565078e+00,  2.32083009e-01],
       [-2.35861703e-01, -2.62064130e+00, -7.84775552e-02],
       [ 1.29215434e+00, -4.51285945e-01, -2.33220394e-02],
       [-2.28947676e+00,  3.72071435e-01,  9.34989662e-02],
       [-2.04476529e+00, -4.40595361e-01, -3.30292923e-01],
       [-1.88267168e+00,  2.91543549e-01,  1.79908489e-02],
       [ 2.27401497e-01, -7.79670305e-01,  1.06632621e-01],
       [-2.23538174e+00,  4.96238752e-01, -1.96273587e-01],
       [ 4.92558369e-02, -7.21576139e-02

In [8]:
pca.components_

array([[ 0.52697587, -0.22992601,  0.58779558,  0.56914569],
       [ 0.34980992,  0.93570534,  0.00902236,  0.04480103],
       [-0.72272541,  0.23850671,  0.12489656,  0.63654017]])

In [9]:
pca.explained_variance_

array([2.8768256 , 0.96829755, 0.17438569])

In [10]:
np.cumsum(pca.explained_variance_)

array([2.8768256 , 3.84512315, 4.01950884])

In [12]:
pca.get_covariance()

array([[ 1.01010101, -0.06239522,  0.87377126,  0.80080311],
       [-0.06239522,  1.01010101, -0.37340705, -0.31071263],
       [ 0.87377126, -0.37340705,  1.01010101,  0.96801244],
       [ 0.80080311, -0.31071263,  0.96801244,  1.01010101]])

In [13]:
pca.get_covariance()

array([[ 1.01010101, -0.06239522,  0.87377126,  0.80080311],
       [-0.06239522,  1.01010101, -0.37340705, -0.31071263],
       [ 0.87377126, -0.37340705,  1.01010101,  0.96801244],
       [ 0.80080311, -0.31071263,  0.96801244,  1.01010101]])

In [ ]:
pca.g